In [18]:
def partsspeech(line):
    tagger=nltk.pos_tag(nltk.word_tokenize(line))
    no_of_nouns=no_of_verbs=no_of_adjectives=no_of_interjunction=no_of_prepositions=no_of_conjunctions=0
    for value,tag in tagger:
        if tag=="NN":
            no_of_nouns+=1
        elif tag=="VBZ":
            no_of_verbs+=1
        elif tag=="JJ":
            no_of_adjectives+=1
        elif tag=="IN":
            no_of_interjunction+=1
        elif tag=="PRP":
            no_of_prepositions+=1
        elif tag=="CC":
            no_of_conjunctions+=1
    return([no_of_nouns,no_of_verbs,no_of_adjectives,no_of_interjunction,no_of_prepositions,no_of_conjunctions])

In [12]:
def specialchars(line):
    words=nltk.word_tokenize(line)
    no_ofalpha=no_ofdigits=no_ofspaces=no_ofanum=0
    for i in words:
        if i.isalpha():
            no_ofalpha+=1
        elif i.isdigit():
            no_ofdigits+=1
        elif i.isspace():
            no_ofspaces+=1
        elif i.isalnum():
            no_ofanum+=1
    return([no_ofalpha,no_ofdigits,no_ofspaces,no_ofanum])

In [54]:
import pandas as pd
import nltk
import numpy as np
from nltk.stem.porter import PorterStemmer
#read the csv file
df=pd.read_csv('C:\\Users\\RENU\\Python Material\\Python workspace\\Python Classroom\\File readwrite\\deceptive.txt',header=None,sep='\n')
#iterating it for each line
features=[]
for line in df[0]:
    temp=[]
    #append no.of characters
    temp.append(len(line))
    tokens=nltk.word_tokenize(line)
    #append the no.of words
    temp.append(len(tokens))
    #append the count of words >3 and 6
    len3=len6=0
    for eachword in tokens:
        if len(eachword)>3:
            len3+=1
        if len(eachword)>6:
            len6+=1
    temp.append(len3)
    temp.append(len6)
    #append no of questionmarks
    temp.append(tokens.count('?'))
    #append no of elipses
    temp.append(tokens.count('...'))
    #append no of exclamations
    temp.append(tokens.count('!'))
    #append no.of sentences
    temp.append(len(line.split('.')))
    #append specialchars
    sc=specialchars(line)
    temp.extend(sc)
    #append parts of speech
    pos=partsspeech(line)
    temp.extend(pos)
    #append no.of bigrams and trigrams
    bigms=list(nltk.bigrams(eachword for eachword in tokens if eachword.isalpha()))
    temp.append(len(bigms))
    #append no.of trigrams
    trigms=list(nltk.ngrams((eachword for eachword in tokens if eachword.isalpha()),3))
    temp.append(len(trigms))
    #append the feature list to include temp
    features.append(temp)
featuresmat=np.array(features)
print("features matrix shape",featuresmat.shape)
print(featuresmat)
#print the data row wise in the features matrix
for rows in range(0,len(df[0])):
    print("Row:",rows)
    print(featuresmat[rows])

features matrix shape (1600, 20)
[[ 445   90   51 ...    2   75   74]
 [1019  215  103 ...    7  194  193]
 [ 819  174   87 ...    3  145  144]
 ...
 [ 477  102   49 ...    4   88   87]
 [ 370   78   37 ...    5   63   62]
 [ 541   89   55 ...    4   77   76]]
Row: 0
[445  90  51  13   0   0   0   6  76   0   0   0  17   3  13  12   3   2
  75  74]
Row: 1
[1019  215  103   37    0    0    1   10  195    1    0    0   32    1
   13   24   17    7  194  193]
Row: 2
[819 174  87  26   0   0   0  16 146   0   0   0  24   0  15  10  13   3
 145 144]
Row: 3
[1083  227  107   30    0    0    1   11  206    1    0    0   30    1
   18   16   21   11  205  204]
Row: 4
[1336  299  138   29    0    0    0   16  267    0    0    0   37    2
   12   22   27   11  266  265]
Row: 5
[4074  851  439  102    0    0    2   32  784    0    0    0  120    2
   46   97   55   25  783  782]
Row: 6
[604 143  51  11   0   0   2   5 120   4   0   0  13   1   4  18  12   5
 119 118]
Row: 7
[735 146  76  25   0  

Row: 671
[449  84  46  19   0   0   3   3  73   0   0   0  11   1   3  10   7   3
  72  71]
Row: 672
[560 105  57  25   0   0   3   3  93   0   0   0  17   1  10  11   4   5
  92  91]
Row: 673
[622 122  59  22   0   0   0   9 114   0   0   0  16   6  11   8  11   5
 113 112]
Row: 674
[589 129  57  14   0   0   0   7 119   0   0   0  17   7   6  12  14   6
 118 117]
Row: 675
[513 101  49  23   0   0   1   8  88   1   0   0  13   1   6  10   9   3
  87  86]
Row: 676
[283  58  32   9   0   0   0   5  53   0   0   0   7   0   8   3   4   3
  52  51]
Row: 677
[285  60  27   9   0   0   0   5  54   0   0   0   8   2   7   6   3   4
  53  52]
Row: 678
[872 178  84  27   0   0   0   9 159   1   0   0  23   0  17  19  12   9
 158 157]
Row: 679
[993 210  94  34   1   0   2  11 179   0   0   0  26   3  17  19  13   7
 178 177]
Row: 680
[280  61  30   8   0   0   2   6  52   0   0   0   5   0   8   1   4   4
  51  50]
Row: 681
[1097  230  126   23    0    0    0   18  206    2    0    0   34    9


Row: 1171
[1106  255  102   27    0    0    3   19  207    8    0    0   35    0
    9   24   17    7  206  205]
Row: 1172
[738 153  76  26   4   0   0  12 123   0   0   0  20   5   8  13   8   2
 122 121]
Row: 1173
[579 109  58  23   0   0   0   9  93   0   0   0  14   3  18   6   8   6
  92  91]
Row: 1174
[1409  279  141   58    0    0    1   15  248    0    0    1   35    5
   22   24   14    9  247  246]
Row: 1175
[739 146  77  23   0   0   0  11 133   0   0   0  21   4   9   9   8  10
 132 131]
Row: 1176
[706 138  75  25   0   1   0  17 120   0   0   0  15   1  13  12  10   5
 119 118]
Row: 1177
[1029  205   96   37    0    1    0   15  179    0    0    1   24    1
   17   19   15    7  178  177]
Row: 1178
[941 200 104  24   0   1   0   8 162   1   0   1  32   6  14  14   0   7
 161 160]
Row: 1179
[421  95  44  12   0   0   0   7  83   0   0   0  10   2   7  10   8   2
  82  81]
Row: 1180
[991 199 101  39   0   0   9   9 180   1   0   0  24   1  12  16  14  11
 179 178]
Row: 1181
